### ISSUE TITLE
Oopsie Woopsy Fucky Wucky Error the 2.4.1 download link for achievement unlocker is 2.4.0.0 version not 2.4.1 version

### ISSUE THREAD

**Issue by cgreen9999** [ItsLogic/Xbox-Achievement-Unlocker#173]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

2.4.0.0

### Tool Section

Home

### What is the bug?

Information
=================================
Tool Version: 2.4.0.0
System Version: 10.0.22631.0
Tool Uptime: 00:03:24.0136859
=================================
Exception
=================================
```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at XAU.ViewModels.Pages.HomeViewModel.TestXAUTH()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
and the 2.4.1 link is downloading the 2.4.0 not the 2.4.1 achievement  unlocker

**Comment by ItsLogic** [comment]
I just forgot to update the version number 💀 
it is actually version 2.4.1 tho
