### ISSUE TITLE
[Bug]: Ooopsie Woopsy Fucky Wucky - Directly when starting

### ISSUE THREAD

**Issue by PlageOne** [ItsLogic/Xbox-Achievement-Unlocker#197]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

2.4.1

### Tool Section

Home

### What is the bug?

Hey,

I get this "Ooopsie Woopsy Fucky Wucky" error message right when I start your tool. I can't use XAU at all. 
Info: I just downloaded the latest version.
Here is the copied error message:

-----------------------------------------------------------------

Information
=================================
Tool Version: 2.4.0.0
System Version: 10.0.22631.0
Tool Uptime: 00:00:11.4594798
=================================
Exception
=================================
```
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at XAU.ViewModels.Pages.HomeViewModel.TestXAUTH()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

-----------------------------------------------------------------

Greetings

**Comment by SyNt3r** [comment]
Information
=================================
Tool Version: 2.5.1.0
System Version: 10.0.22621.0
Tool Uptime: 00:00:32.8950885
=================================
Exception
=================================
```
System.FormatException: The input string '70.42' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Single.Parse(String s)
   at XAU.ViewModels.Pages.AchievementsViewModel.LoadAchievements()
   at XAU.ViewModels.Pages.AchievementsViewModel.InitializeViewModel()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Just after update from 2.4.1 to 2.5.1

**Comment by M4u87** [comment]
Same problem
Information
=================================
Tool Version: 2.5.1.0
System Version: 10.0.19045.0
Tool Uptime: 00:00:12.4143171
=================================
Exception
=================================
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XAU.ViewModels.Pages.GamesViewModel.AddGame(Int32 index)
   at XAU.ViewModels.Pages.GamesViewModel.FilterGames()
   at XAU.ViewModels.Pages.GamesViewModel.LoadGame()
   at XAU.ViewModels.Pages.GamesViewModel.GetGamesList()
   at XAU.ViewModels.Pages.GamesViewModel.InitializeViewModel()
   at XAU.ViewModels.Pages.GamesViewModel.OnNavigatedTo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
