### ISSUE TITLE
[Bug]: Spoofer will stop after running for more than 5 hours.

### ISSUE THREAD

**Issue by Norsk-SkogKatt** [ItsLogic/Xbox-Achievement-Unlocker#226]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

2.4.1

### Tool Section

Misc- Spoofer

### What is the bug?

Information
=================================
Tool Version: 2.4.0.0
System Version: 10.0.22631.0
Tool Uptime: 11:10:48.7456874
=================================
Exception
=================================
```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at XAU.ViewModels.Pages.MiscViewModel.SpoofGame()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Norsk-SkogKatt** [comment]
log:
Information
=================================
Tool Version: 2.4.0.0
System Version: 10.0.22631.0
Tool Uptime: 11:14:38.2432711
=================================
Exception
=================================
```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at XAU.ViewModels.Pages.MiscViewModel.SpoofGame()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
