### ISSUE TITLE
[Bug]: error darksiders genesis

### ISSUE THREAD

**Issue by hannesdelbeke** [ItsLogic/Xbox-Achievement-Unlocker#283]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

2.7

### Tool Section

Home

### What is the bug?

```
Information
=================================
Tool Version: 2.7.0.0
System Version: 10.0.19045.0
Tool Uptime: 00:06:04.9902716
=================================
Exception
=================================

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at XAU.ViewModels.Pages.AchievementsViewModel.SpoofGame()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

when trying to unlock darksiders genesis

**Comment by hannesdelbeke** [comment]
worked after restart and retry
