### ISSUE TITLE
Still unable to execute .exe

### ISSUE THREAD

**Issue by Nanofats-Teio** [ItsLogic/Xbox-Achievement-Unlocker#30]
Nothing happens when opening Xbox.Achievement.Unlocker.exe 1.6 update; nothing happens when run as admin.

Already added as an exception for Windows Defender.

While Xbox Achievement Unlocker.exe in release 1.3 zip file can be executed, gamer tag, gamer score, XUID and game library loaded normally. However by clicking on a certain game title, following error message popped up:

Nullable object must have a value.

System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Xbox_Achievement_Unlocker.MainWindow.LoadAchievementList(Object sender, EventArgs e) in C:\Users\comamnds\source\repos\Xbox-Achievement-Unlocker\MainWindow.cs:line 132
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

**Comment by ItsLogic** [comment]
try installing this
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.14-windows-x64-installer
