### ISSUE TITLE
[Bug]: it pop up when i open it

### ISSUE THREAD

**Issue by AmzingLily** [ItsLogic/Xbox-Achievement-Unlocker#331]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

2.7.0.0

### Tool Section

Home

### What is the bug?

Information
=================================
Tool Version: 2.7.0.0
System Version: 10.0.22631.0
Tool Uptime: 00:00:01.9808954
=================================
Exception
=================================
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GithubRestApi.GetReleaseVersionAsync()
   at XAU.ViewModels.Pages.HomeViewModel.CheckForToolUpdates()
   at XAU.ViewModels.Pages.HomeViewModel.InitializeViewModel()
   at XAU.ViewModels.Pages.HomeViewModel.OnNavigatedTo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by AmzingLily** [comment]
it doesnt matter, i can still use, it just pop up :)
