### ISSUE TITLE
[Bug]: can't open

### ISSUE THREAD

**Issue by Zhengshihangcn** [ItsLogic/Xbox-Achievement-Unlocker#350]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

2.7

### Tool Section

Home

### What is the bug?

Information
=================================
Tool Version: 2.7.0.0
System Version: 10.0.22631.0
Tool Uptime: 00:00:59.7282743
=================================
Exception
=================================
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GithubRestApi.GetReleaseVersionAsync()
   at XAU.ViewModels.Pages.HomeViewModel.CheckForToolUpdates()
   at XAU.ViewModels.Pages.HomeViewModel.InitializeViewModel()
   at XAU.ViewModels.Pages.HomeViewModel.OnNavigatedTo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NextLVLHasH** [comment]
this isnt a bug, you have pushed too many requests over a 24 hour period, you can tell this from your 403 (rate limit exceeded).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded). Restart the xbox app it may fix it via a token switch / regen

**Comment by ipisano** [comment]
I don't know about OP, but I have the same error and I have no clue as to why I would be getting rate limited, I tried restarting the Xbox app and even my whole PC to no avail. I did use this tool in the past, the last time was about a month ago or so.

**Comment by NextLVLHasH** [comment]
> I don't know about OP, but I have the same error and I have no clue as to why I would be getting rate limited, I tried restarting the Xbox app and even my whole PC to no avail. I did use this tool in the past, the last time was about a month ago or so.

You couldnt help it. Github went down
