### ISSUE TITLE
[Bug]: Unhandled exception in Game Spoofer

### ISSUE THREAD

**Issue by Victor7095** [ItsLogic/Xbox-Achievement-Unlocker#48]
### What version of the app were you running?

1.7

### Winver

Win11

### Have I checked if the bug was reported?

Yes

### What is the bug?

Error happens when clicking Start button on Game Spoofer Dialog.

Exception:
`Index out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

Log:
```
Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Xbox_Achievement_Unlocker.Game_Spoofer.BTN_Spoof_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)


************** Assemblies Carregados **************
System.Private.CoreLib
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.CoreLib.dll
----------------------------------------
Xbox Achievement Unlocker
    Versão do Assembly: 1.7.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1823.27201
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1823.27201
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.dll
----------------------------------------
Memory
    Versão do Assembly: 1.2.23.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
netstandard
    Versão do Assembly: 2.1.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/netstandard.dll
----------------------------------------
System.Net.Http
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 6.0.1823.27201
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Runtime.Loader
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1823.27201
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/pt-BR/System.Windows.Forms.resources.dll
----------------------------------------
System.Numerics.Vectors
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Memory
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Memory.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.ObjectModel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ObjectModel.dll
----------------------------------------
System.Linq
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Linq.dll
----------------------------------------
System.Private.Uri
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.Uri.dll
----------------------------------------
System.Collections.NonGeneric
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.NonGeneric.dll
----------------------------------------
Newtonsoft.Json
    Versão do Assembly: 13.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Linq.Expressions
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Linq.Expressions.dll
----------------------------------------
Microsoft.CSharp
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/Microsoft.CSharp.dll
----------------------------------------
System.ComponentModel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.dll
----------------------------------------
System.Diagnostics.Process
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.Process.dll
----------------------------------------
System.Collections.Concurrent
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Sockets
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.IO.Compression
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.IO.Compression.dll
----------------------------------------
System.Runtime.Numerics
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.Numerics.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.CoreLib.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading.Tasks.Parallel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.Tasks.Parallel.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1823.26907
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.Immutable.dll
----------------------------------------

************** Depuração JIT **************
```

**Comment by Victor7095** [comment]
Tried again later and it worked normally. I believe it was an issue with my network somehow. But it would be useful anyway to handle the exception and show a more meaningful message

**Comment by ItsLogic** [comment]
yeah the game spoofer has absolutely no error handling. I will polish it up soon enough
